/** Short tooltip descriptions for quiz values */
export const VALUE_DESCRIPTIONS: Record<string, string> = {
  "Affection (love and caring)": "Expressing warmth and tender care toward others",
  Caring: "Showing genuine concern for others' wellbeing",
  Dependability: "Being someone others can consistently count on",
  Forgiveness: "Releasing resentment and offering second chances",
  Friendship: "Cultivating deep, loyal bonds with others",
  Fun: "Embracing lightheartedness and enjoyment in life",
  Giving: "Generously sharing your time, resources, and energy",
  Gratitude: "Recognizing and appreciating what you have",
  Growth: "Continuously evolving and becoming better",
  Honesty: "Speaking and living truthfully, even when difficult",
  Joy: "Finding deep, lasting happiness beyond circumstances",
  Kindness: "Acting with gentleness and goodwill toward all",
  Loyalty: "Standing faithfully by those you care about",
  "Open and Honest (i.e. being around people who are)": "Surrounding yourself with transparent, genuine people",
  Patience: "Remaining calm and steady through difficulty",
  Purpose: "Living with clear intention and direction",
  Trustworthiness: "Being worthy of others' confidence",
  "Adding Value": "Making things better than you found them",
  "Ethical Practice": "Adhering to moral principles in all actions",
  Humor: "Using laughter to connect and cope",
  Learning: "Pursuing knowledge and understanding relentlessly",
  "Personal Growth & Development (living up to the fullest potential)": "Striving to reach your highest potential",
  Religion: "Practicing devotion to your faith tradition",
  Truth: "Pursuing what is real and authentic",
  "Meaningful Work": "Doing work that matters and fulfills you",
  Wisdom: "Applying deep understanding to life's challenges",
  Family: "Prioritizing your family bonds and wellbeing",
  "Having a Family": "Building and nurturing a family of your own",
  Beauty: "Appreciating and creating aesthetic excellence",
  Discernment: "Making wise, thoughtful decisions",
  Charity: "Giving selflessly to those in need",
  "Close Relationships": "Maintaining deep, intimate connections",
  Community: "Building and participating in shared life with others",
  Knowledge: "Acquiring deep understanding of the world",
  "Quality Relationships": "Investing in meaningful, healthy bonds",
  Reliability: "Consistently following through on commitments",
  Chivalry: "Practicing honor, courtesy, and selfless service",
  Considerate: "Thinking about how your actions affect others",
  Courage: "Facing fear and difficulty with resolve",
  Happiness: "Pursuing and cultivating a joyful life",
  Life: "Cherishing and protecting the gift of existence",
  Perseverance: "Pressing forward despite obstacles",
  Communication: "Expressing yourself clearly and listening well",
  Compassion: "Feeling and acting on empathy for others' suffering",
  Cheerfulness: "Maintaining a positive, uplifting attitude",
  Clarity: "Seeking and providing clear understanding",
  Sharing: "Freely giving of what you have",
  Togetherness: "Being present and united with others",
  Authenticity: "Being genuinely yourself in all situations",
  Excellence: "Striving for the highest quality in all you do",
  Energy: "Bringing vitality and drive to your endeavors",
  Leadership: "Guiding and inspiring others toward a vision",
  Confidence: "Trusting in your abilities and worth",
  God: "Centering your life on the divine",
  Love: "Giving and receiving unconditional care",
  Nurturing: "Helping others grow and flourish",
  Tenderness: "Approaching others with gentle sensitivity",
  Trust: "Building and maintaining mutual confidence",
  Humility: "Recognizing your limitations with grace",
  "Team/Teamwork": "Collaborating effectively toward shared goals",
  Awareness: "Being present and perceptive to your surroundings",
  Creativity: "Expressing original ideas and solutions",
  Health: "Caring for your physical and mental wellbeing",
  Intention: "Living deliberately and purposefully",
  Value: "Recognizing inherent worth in people and things",
  Coaching: "Helping others unlock their potential",
  Fairness: "Treating everyone with impartial justice",
  Honor: "Living with dignity and moral principle",
  Integrity: "Aligning your actions with your values",
  Justice: "Pursuing what is right and equitable",
  Nature: "Connecting with and respecting the natural world",
  Quality: "Demanding excellence in all endeavors",
  Respect: "Honoring the dignity of every person",
  "Responsibility and accountability": "Owning your actions and their consequences",
  Contribution: "Adding meaningfully to the world around you",
  "Achievement/Drive": "Pursuing ambitious goals with determination",
  "Helping Other People": "Dedicating yourself to others' welfare",
  "Self-determinism": "Choosing your own path and identity",
  "Self-Respect": "Honoring your own worth and boundaries",
  Companionship: "Sharing life's journey with others",
  Conscientiousness: "Being thorough, careful, and responsible",
  Conviction: "Standing firm in your beliefs",
  Cooperation: "Working harmoniously with others",
  Courteousness: "Treating others with polite respect",
  Discovery: "Exploring new ideas, places, and possibilities",
  "Helping Society": "Contributing to the common good",
  "Making a difference": "Creating positive change in the world",
  "Public Service": "Serving your community and country",
  Spontaneity: "Embracing the unexpected with openness",
  Adaptability: "Adjusting gracefully to change",
  Commitment: "Dedicating yourself fully to what matters",
  Presence: "Being fully attentive in each moment",
  Unity: "Fostering harmony and oneness with others",
  Connection: "Building deep, meaningful bonds",
  Playfulness: "Approaching life with lightness and fun",
  Involvement: "Actively participating in what matters to you",
  Music: "Finding meaning and joy through musical expression",
  "Order (tranquility, stability, conformity)": "Creating calm structure in your life",
  Security: "Ensuring safety and stability for yourself and others",
  Simplicity: "Finding beauty and peace in less",
  Excitement: "Seeking thrilling, stimulating experiences",
  "Inner Harmony": "Achieving peace and balance within yourself",
  Attractiveness: "Valuing and cultivating personal appeal",
  Competence: "Building mastery and capability",
  Intimacy: "Sharing deep emotional and physical closeness",
  Passion: "Pursuing what sets your soul on fire",
  Vulnerability: "Being courageously open and authentic",
  Aesthetic: "Appreciating beauty in art, design, and life",
  Certainty: "Seeking clarity and confidence in decisions",
  "Economic Security": "Building financial stability and safety",
  Empathy: "Understanding and sharing others' feelings",
  Enthusiasm: "Bringing infectious energy to everything you do",
  Freedom: "Living without unnecessary constraints",
  Independence: "Being self-reliant and autonomous",
  Travel: "Exploring the world and broadening horizons",
  Vigor: "Living with physical and mental strength",
  "Advancement and Promotion": "Progressing in your career and status",
  Adventure: "Seeking bold, exciting experiences",
  Affinity: "Feeling natural connection and kinship",
  Aliveness: "Feeling fully awake and engaged in life",
  Arts: "Creating and appreciating artistic expression",
  Articulate: "Expressing yourself with precision and eloquence",
  Bliss: "Experiencing profound, transcendent joy",
  "Challenging Problems": "Thriving on complex intellectual puzzles",
  "Change and Variety": "Embracing diversity of experience",
  Charisma: "Inspiring and attracting others naturally",
  Competition: "Striving to win and excel",
  Congruence: "Living in alignment with your beliefs",
  Decisiveness: "Making clear, confident choices",
  Democracy: "Valuing equal voice and participation",
  "Ecological Awareness": "Protecting and respecting the environment",
  Effectiveness: "Producing meaningful results efficiently",
  Efficiency: "Achieving maximum output with minimum waste",
  Endurance: "Sustaining effort through long challenges",
  Environment: "Caring for the world around you",
  Equality: "Treating all people as inherently equal",
  Expertise: "Developing deep, specialized knowledge",
  Expression: "Communicating your inner truth outwardly",
  Fame: "Being widely known and recognized",
  "Fast Living": "Embracing an intense, high-energy lifestyle",
  "Fast-Paced Work": "Thriving in dynamic, rapid environments",
  "Financial Gain": "Building wealth and financial success",
  Flexibility: "Bending without breaking when circumstances shift",
  Focus: "Directing sustained attention to what matters most",
  Heart: "Leading and living from emotional depth",
  Inclusive: "Welcoming and embracing all people",
  "Influencing Others": "Shaping others' thoughts and actions positively",
  Inspiration: "Sparking motivation and possibility in others",
  "Intellectual Status": "Being recognized for intelligence and knowledge",
  Intelligence: "Valuing and developing mental acuity",
  "Job Tranquility": "Finding peace and calm in your work",
  Leverage: "Maximizing impact through strategic advantage",
  Location: "Being where you feel most alive and connected",
  "Market Position": "Achieving competitive standing and influence",
  Mentorship: "Guiding others through wisdom and experience",
  Meditation: "Practicing stillness and inner reflection",
  Merit: "Being rewarded based on ability and effort",
  "Money/Making Money": "Creating financial abundance",
  Openness: "Being receptive to new ideas and experiences",
  Peace: "Cultivating inner and outer tranquility",
  Perception: "Seeing the world with depth and clarity",
  "Physical Challenge": "Testing and pushing your physical limits",
  Pleasure: "Savoring enjoyable experiences",
  "Power and Authority": "Wielding influence and control responsibly",
  Privacy: "Protecting your personal space and boundaries",
  Probability: "Making decisions based on likelihood and evidence",
  Productivity: "Creating consistent, valuable output",
  Purity: "Maintaining moral and spiritual cleanliness",
  Rational: "Making decisions through logic and reason",
  Receptivity: "Being open to receiving from others",
  "Recognition (respect from others, status)": "Being acknowledged and valued by others",
  Reputation: "Building and maintaining a respected name",
  Resolution: "Seeing things through to completion",
  Resolve: "Maintaining firm determination",
  Resourcefulness: "Finding creative solutions with limited resources",
  Sensitivity: "Being attuned to subtle feelings and nuances",
  Sensuality: "Engaging fully with physical and sensory experience",
  Serenity: "Maintaining calm composure regardless of circumstances",
  Sophistication: "Appreciating refinement and cultural depth",
  Soul: "Connecting with your deepest spiritual essence",
  Spirit: "Living with vigor and transcendent purpose",
  Spiritual: "Pursuing connection with something greater than yourself",
  Stability: "Building a steady, reliable foundation",
  Strength: "Drawing on inner and outer power",
  Status: "Achieving social standing and recognition",
  Success: "Achieving your goals and aspirations",
  "Supervising Others": "Leading and managing teams effectively",
  Synergy: "Creating outcomes greater than the sum of parts",
  Technology: "Embracing innovation and digital tools",
  "Time Freedom": "Having control over how you spend your time",
  Vision: "Seeing and pursuing a compelling future",
  Vitality: "Living with robust health and energy",
  Wealth: "Accumulating resources and abundance",
};
